version: "3.8"
services:
  ubuntu1:
    build: .
    networks:
      - vulture_net
    command: tail -f /dev/null

  ubuntu2:
    build: .
    command: tail -f /dev/null
    networks:
      - vulture_net

networks:
  vulture_net:
    driver: bridge
