version: "3.8"
services:
  ubuntu1:
    build: .
    networks:
      - vulture_net
    command: tail -f /dev/null
    ports:
      - "8080:4444"
    cap_add:
      - NET_ADMIN
    volumes:
      - srvpublic:/home/public
  ubuntu2:
    build: .
    command: tail -f /dev/null
    ports:
      - "8081:4444"
    networks:
      - vulture_net
    cap_add:
      - NET_ADMIN
    volumes:
      - srvpublic:/home/public

networks:
  vulture_net:
    driver: bridge

volumes:
  srvpublic:
